version: '3'
services:
  web:
    image: "ubuntu:18.04"
    ports:
      - "8080:80"
      - "9990:443"
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
