version: '2'
services:
  web:
    image: "ubuntu:18.04"
    ports:
      - "8080:80"
      - "9990:443"
      links:
        - basededatos:mimariadb
   basedatos:
   image: some-mariadb
   ports:
    - "3306:3306"
