version: "3.3"

services:

  web:
   build: ./docker-prestashop/web
   ports:
    - "9990:80"
    - "9993:443"
   
   volumes:
    -./prestashop:/var/www/html
   
   db:
    images: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=prestashop
