version: '3.3'
services:
  web:
    build: ./m9
    ports:
      - "9494:80"
      - "9993:443"
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=prestashop
