version: '3.3'
services:
  web:
    build: ./web
    ports:
      - "9090:80"
      - "9993:443"
    volumes:
      - ./prestashop:/var/www/html
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=prestashop
